[project]
name = "skn35-2nd-2team"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "YOONJUNG", email = "chayj0421@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "lightgbm>=4.7.0",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
    "xgboost>=3.4.1",
]

[project.scripts]
skn35-2nd-2team = "skn35_2nd_2team:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
